### ISSUE TITLE
SimpleNode客户端同步数据时间长，挖矿慢人一步怎么办？

### ISSUE THREAD

**Issue by gon-superman** [simplechain-org/simplenode#1]
首先，为什么慢？
      SimpleNode客户端启动后要从网络中的其它节点同步数据，
同步的速度与客户端连接的节点数量和网络有关，但是呢simplenode默认的连接节点较少，
并且连接数多会造成拥堵，所以就造成了漫长等待。

然后，怎么解决呢？
      SimpleChain网络是支持客户端自己配置静态节点的，下载[static-nodes.json](https://wallet.simplechain.com/version/static-nodes.json)并根据系统平台放在指定数据目录即可。

Mac: ~/Library/SimpleNodeData
Linux: ~/SimpleNodeData
Windows: %APPDATA%\SimpleNodeData

另外，您也可以把自己的节点提供出来（通过微信、微博、github等一切可能的方式）供更多的人连接。

**Comment by saintfeng** [comment]
请教用sipe的话放在哪个目录？谢谢。

**Comment by gon-superman** [comment]
windows: %AppData%\Simplechain
mac:~/Library/Simplechain
linux:~/Simplechain


Original Message
Sender:Feng Linotifications@github.com
Recipient:simplechain-org/simplenodesimplenode@noreply.github.com
Cc:qupenghuiwaterlord@vip.qq.com; Authorauthor@noreply.github.com
Date:Thursday, Jan 17, 2019 17:56
Subject:Re: [simplechain-org/simplenode] SimpleNode客户端同步数据时间长，挖矿慢人一步怎么办？ (#1)


请教用sipe的话放在哪个目录？谢谢。
